/* This file is generated by the nymea build system. Any changes to this file will *
 * be lost. If you want to change this file, edit the plugin's json file.          */

#ifndef PLUGININFO_H
#define PLUGININFO_H

#include "typeutils.h"

#include <QLoggingCategory>
#include <QObject>

extern "C" const QString libnymea_api_version() { return QString("6.0.0");}

Q_DECLARE_LOGGING_CATEGORY(dcWs281xspi)
Q_LOGGING_CATEGORY(dcWs281xspi, "Ws281xspi")

PluginId pluginId = PluginId("{2a1be833-4457-4bd3-bd96-ea74b62e6348}");
VendorId ws281xspiVendorId = VendorId("{599337a2-cfc8-4ced-952b-ded34e2f4cf7}");
ThingClassId ws281xspiThingClassId = ThingClassId("{e19c2e0f-4252-481d-9005-7b103bfacf12}");
ParamTypeId ws281xspiThingSpiPinParamTypeId = ParamTypeId("{701790ef-2dd8-4166-a18f-0af20877d25c}");
ParamTypeId ws281xspiThingLengthParamTypeId = ParamTypeId("{9c2d0d6a-7dd8-4f2e-9363-63b9e3d89254}");
StateTypeId ws281xspiBrightnessStateTypeId = StateTypeId("{7fc8b313-8609-46a1-a7c2-2a61993825b6}");
StateTypeId ws281xspiColorStateTypeId = StateTypeId("{24644623-f7d4-47e6-a259-c564a7721b9e}");
StateTypeId ws281xspiPowerStateTypeId = StateTypeId("{23cb9794-f637-4861-a885-2237b80aacb9}");
EventTypeId ws281xspiBrightnessEventTypeId = EventTypeId("{7fc8b313-8609-46a1-a7c2-2a61993825b6}");
ParamTypeId ws281xspiBrightnessEventBrightnessParamTypeId = ParamTypeId("{7fc8b313-8609-46a1-a7c2-2a61993825b6}");
EventTypeId ws281xspiColorEventTypeId = EventTypeId("{24644623-f7d4-47e6-a259-c564a7721b9e}");
ParamTypeId ws281xspiColorEventColorParamTypeId = ParamTypeId("{24644623-f7d4-47e6-a259-c564a7721b9e}");
EventTypeId ws281xspiPowerEventTypeId = EventTypeId("{23cb9794-f637-4861-a885-2237b80aacb9}");
ParamTypeId ws281xspiPowerEventPowerParamTypeId = ParamTypeId("{23cb9794-f637-4861-a885-2237b80aacb9}");
ActionTypeId ws281xspiBrightnessActionTypeId = ActionTypeId("{7fc8b313-8609-46a1-a7c2-2a61993825b6}");
ParamTypeId ws281xspiBrightnessActionBrightnessParamTypeId = ParamTypeId("{7fc8b313-8609-46a1-a7c2-2a61993825b6}");
ActionTypeId ws281xspiColorActionTypeId = ActionTypeId("{24644623-f7d4-47e6-a259-c564a7721b9e}");
ParamTypeId ws281xspiColorActionColorParamTypeId = ParamTypeId("{24644623-f7d4-47e6-a259-c564a7721b9e}");
ActionTypeId ws281xspiPowerActionTypeId = ActionTypeId("{23cb9794-f637-4861-a885-2237b80aacb9}");
ParamTypeId ws281xspiPowerActionPowerParamTypeId = ParamTypeId("{23cb9794-f637-4861-a885-2237b80aacb9}");

const QString translations[] {
    //: The name of the ParamType (ThingClass: ws281xspi, ActionType: brightness, ID: {7fc8b313-8609-46a1-a7c2-2a61993825b6})
    QT_TRANSLATE_NOOP("ws281xspi", "Brightness"),

    //: The name of the ParamType (ThingClass: ws281xspi, EventType: brightness, ID: {7fc8b313-8609-46a1-a7c2-2a61993825b6})
    QT_TRANSLATE_NOOP("ws281xspi", "Brightness"),

    //: The name of the StateType ({7fc8b313-8609-46a1-a7c2-2a61993825b6}) of ThingClass ws281xspi
    QT_TRANSLATE_NOOP("ws281xspi", "Brightness"),

    //: The name of the EventType ({7fc8b313-8609-46a1-a7c2-2a61993825b6}) of ThingClass ws281xspi
    QT_TRANSLATE_NOOP("ws281xspi", "Brightness changed"),

    //: The name of the ParamType (ThingClass: ws281xspi, ActionType: color, ID: {24644623-f7d4-47e6-a259-c564a7721b9e})
    QT_TRANSLATE_NOOP("ws281xspi", "Color"),

    //: The name of the ParamType (ThingClass: ws281xspi, EventType: color, ID: {24644623-f7d4-47e6-a259-c564a7721b9e})
    QT_TRANSLATE_NOOP("ws281xspi", "Color"),

    //: The name of the StateType ({24644623-f7d4-47e6-a259-c564a7721b9e}) of ThingClass ws281xspi
    QT_TRANSLATE_NOOP("ws281xspi", "Color"),

    //: The name of the EventType ({24644623-f7d4-47e6-a259-c564a7721b9e}) of ThingClass ws281xspi
    QT_TRANSLATE_NOOP("ws281xspi", "Color changed"),

    //: The name of the ParamType (ThingClass: ws281xspi, Type: thing, ID: {9c2d0d6a-7dd8-4f2e-9363-63b9e3d89254})
    QT_TRANSLATE_NOOP("ws281xspi", "Length"),

    //: The name of the ParamType (ThingClass: ws281xspi, ActionType: power, ID: {23cb9794-f637-4861-a885-2237b80aacb9})
    QT_TRANSLATE_NOOP("ws281xspi", "Power"),

    //: The name of the ParamType (ThingClass: ws281xspi, EventType: power, ID: {23cb9794-f637-4861-a885-2237b80aacb9})
    QT_TRANSLATE_NOOP("ws281xspi", "Power"),

    //: The name of the StateType ({23cb9794-f637-4861-a885-2237b80aacb9}) of ThingClass ws281xspi
    QT_TRANSLATE_NOOP("ws281xspi", "Power"),

    //: The name of the EventType ({23cb9794-f637-4861-a885-2237b80aacb9}) of ThingClass ws281xspi
    QT_TRANSLATE_NOOP("ws281xspi", "Power changed"),

    //: The name of the ParamType (ThingClass: ws281xspi, Type: thing, ID: {701790ef-2dd8-4166-a18f-0af20877d25c})
    QT_TRANSLATE_NOOP("ws281xspi", "SPI Pin"),

    //: The name of the ActionType ({7fc8b313-8609-46a1-a7c2-2a61993825b6}) of ThingClass ws281xspi
    QT_TRANSLATE_NOOP("ws281xspi", "Set brightness"),

    //: The name of the ActionType ({24644623-f7d4-47e6-a259-c564a7721b9e}) of ThingClass ws281xspi
    QT_TRANSLATE_NOOP("ws281xspi", "Set color"),

    //: The name of the ActionType ({23cb9794-f637-4861-a885-2237b80aacb9}) of ThingClass ws281xspi
    QT_TRANSLATE_NOOP("ws281xspi", "Set power"),

    //: The name of the ThingClass ({e19c2e0f-4252-481d-9005-7b103bfacf12})
    QT_TRANSLATE_NOOP("ws281xspi", "Ws281xspi"),

    //: The name of the vendor ({599337a2-cfc8-4ced-952b-ded34e2f4cf7})
    QT_TRANSLATE_NOOP("ws281xspi", "Ws281xspi"),

    //: The name of the plugin ws281xspi ({2a1be833-4457-4bd3-bd96-ea74b62e6348})
    QT_TRANSLATE_NOOP("ws281xspi", "Ws281xspi")
};

#endif // PLUGININFO_H
